### GET Data
GET http://localhost:4004/browse/Books?

### Decreased Stock Item
POST http://localhost:4004/browse/decreasedStock
Content-Type: application/json

{
    "book": "4527855e-a764-4daa-a5e9-b932d22540c5",
    "quantity": 5
}

### Increased Stock Item
POST http://localhost:4004/browse/increasedStock
Content-Type: application/json

{
    "book": "4527855e-a764-4daa-a5e9-b932d22540c5",
    "quantity": 10
}

### Submit book order
POST http://localhost:4004/browse/submitOrder
Content-Type: application/json

{
    "customer": "14859865-2ab6-44e9-8221-c9fb0d351db6",
    "book": "4527855e-a764-4daa-a5e9-b932d22540c5",
    "quantity": 10
}

### Process Order
POST http://localhost:4004/browse/processOrder
Content-Type: application/json

{
    "order": "89c65a6d-4ebf-4fec-b566-c66097a7088c"
}

### Ship Order
POST http://localhost:4004/browse/shipOrder
Content-Type: application/json

{
    "order": "89c65a6d-4ebf-4fec-b566-c66097a7088c"
}

### Cancel Order
POST http://localhost:4004/browse/cancelOrder
Content-Type: application/json

{
    "order": "89c65a6d-4ebf-4fec-b566-c66097a7088c"
}

### Delete Order directly from db
DELETE http://localhost:4004/browse/Orders(424db7de-6c2f-4c40-bc2e-9e1b0dbefeaa)

### Create Customer
POST http://localhost:4004/browse/Customers
Content-Type: application/json

{
    "name": "Iqbal Nur Akbar",
    "email": "iqbal@gmail.com",
    "address": "Bandung, Indonesia"
}

### Show Order Summary
POST http://localhost:4004/browse/getOrderSummary
Content-Type: application/json

{
    "customer": "14859865-2ab6-44e9-8221-c9fb0d351db6"
}